# Generated by Django 4.1.6 on 2023-03-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='descrip',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
