# Generated by Django 4.1.6 on 2023-03-05 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactus',
            new_name='contactu',
        ),
    ]
