# Generated by Django 4.1.6 on 2023-03-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_rename_contactus_contactu'),
    ]

    operations = [
        migrations.AddField(
            model_name='signform',
            name='name',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
