# Generated by Django 4.1.6 on 2023-03-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_signform_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signform',
            name='name',
        ),
    ]
