# Generated by Django 4.1.5 on 2023-03-06 07:38

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_remove_signform_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='updimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imag', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imag')),
            ],
        ),
    ]
