# Generated by Django 4.1.5 on 2023-03-07 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_updimage_address_de_updimage_fname_updimage_lname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='updimage',
            new_name='updateprofile',
        ),
    ]
