# Generated by Django 4.1.5 on 2023-03-09 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_rename_updimage_updateprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='updateprofile',
        ),
    ]
