# Generated by Django 4.1.5 on 2023-03-15 07:32

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_signform_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='proimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.RemoveField(
            model_name='signform',
            name='name',
        ),
    ]
