# Generated by Django 4.1.5 on 2023-03-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0013_proimage_remove_signform_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='proimage',
            name='name',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
