# Generated by Django 4.1.5 on 2023-03-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0015_remove_proimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='proimage',
            name='user',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
