# Generated by Django 4.1.5 on 2023-05-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0016_proimage_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='leavecomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adds_id', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=400)),
            ],
        ),
    ]
