# Generated by Django 4.1.5 on 2023-05-11 05:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0017_leavecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
