# Generated by Django 4.1.5 on 2023-05-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0019_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='Permission',
            field=models.BooleanField(default=False),
        ),
    ]
