# Generated by Django 4.1.5 on 2023-05-15 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0020_add_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add',
            name='descrip',
        ),
    ]
